package com.officearcade.server.notifications;

public enum NotificationType {
    CHALLENGE_CREATED,
    CHALLENGE_CONFIRMED,
    CHALLENGE_REJECTED,
    CHALLENGE_DISPUTE_RESOLVED,
    RESPECT_GAINED,
    KARMA_APPLIED,
    STORE_PURCHASE_SUCCESS,
    ITEM_EQUIPPED,
    MODERATION_STATUS_UPDATE,
    REPORT_STATUS_UPDATE,
    GAME_RESULT
}
